// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TutoFlow.ApiService.Data;

#nullable disable

namespace TutoFlow.ApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223233110_AddUserAndCenterModels")]
    partial class AddUserAndCenterModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "join_method", new[] { "none", "invitation", "self_request", "admin_added", "by_link" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "membership_status", new[] { "none", "active", "left", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permissions_level", new[] { "none", "super_admin", "center_admin", "moderator" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "none", "client", "tutor", "admin", "super_admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "work_model", new[] { "none", "individual", "center" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.AdminProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("integer")
                        .HasColumnName("center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_title");

                    b.Property<int>("PermissionsLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_level");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("idx_admin_profiles_center_id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("admin_profiles", (string)null);
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("LegalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Inn")
                        .IsUnique()
                        .HasDatabaseName("idx_centers_inn")
                        .HasFilter("inn IS NOT NULL");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_centers_name");

                    b.ToTable("centers", null, t =>
                        {
                            t.HasCheckConstraint("chk_centers_inn", "inn ~ '^\\d{10,12}$'");
                        });
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.CenterMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_admin_id");

                    b.Property<int>("CenterId")
                        .HasColumnType("integer")
                        .HasColumnName("center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("JoinMethod")
                        .HasColumnType("integer")
                        .HasColumnName("join_method");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("text")
                        .HasColumnName("leave_reason");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int>("TutorProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("tutor_profile_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByAdminId");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("idx_center_membership_center_id");

                    b.HasIndex("JoinedAt")
                        .HasDatabaseName("idx_center_membership_joined_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_center_membership_status");

                    b.HasIndex("TutorProfileId")
                        .HasDatabaseName("idx_center_membership_tutor_profile_id");

                    b.HasIndex("CenterId", "TutorProfileId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_active_membership")
                        .HasFilter("status = 'active'");

                    b.ToTable("center_membership", (string)null);
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsAdult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_adult");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("client_profiles", (string)null);
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("client_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<short?>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<bool>("IsSelf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_self");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId")
                        .HasDatabaseName("idx_students_client_profile_id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("idx_students_full_name");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("chk_students_grade", "grade BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.TutorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Education")
                        .HasColumnType("text")
                        .HasColumnName("education");

                    b.Property<short?>("ExperienceYears")
                        .HasColumnType("smallint")
                        .HasColumnName("experience_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("ProfileVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("profile_verified");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialization");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkModel")
                        .HasColumnType("integer")
                        .HasColumnName("work_model");

                    b.HasKey("Id");

                    b.HasIndex("Specialization")
                        .HasDatabaseName("idx_tutor_profiles_specialization");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WorkModel")
                        .HasDatabaseName("idx_tutor_profiles_work_model");

                    b.ToTable("tutor_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_tutor_experience", "experience_years >= 0");

                            t.HasCheckConstraint("chk_tutor_hourly_rate", "hourly_rate > 0");
                        });
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.AdminProfile", b =>
                {
                    b.HasOne("TutoFlow.ApiService.Data.Models.Center", "Center")
                        .WithMany("AdminProfiles")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoFlow.ApiService.Data.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("TutoFlow.ApiService.Data.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.CenterMembership", b =>
                {
                    b.HasOne("TutoFlow.ApiService.Data.Models.AdminProfile", "ApprovedByAdmin")
                        .WithMany("ApprovedMemberships")
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TutoFlow.ApiService.Data.Models.Center", "Center")
                        .WithMany("Memberships")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoFlow.ApiService.Data.Models.TutorProfile", "TutorProfile")
                        .WithMany("Memberships")
                        .HasForeignKey("TutorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("Center");

                    b.Navigation("TutorProfile");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.ClientProfile", b =>
                {
                    b.HasOne("TutoFlow.ApiService.Data.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("TutoFlow.ApiService.Data.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.Student", b =>
                {
                    b.HasOne("TutoFlow.ApiService.Data.Models.ClientProfile", "ClientProfile")
                        .WithMany("Students")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.TutorProfile", b =>
                {
                    b.HasOne("TutoFlow.ApiService.Data.Models.User", "User")
                        .WithOne("TutorProfile")
                        .HasForeignKey("TutoFlow.ApiService.Data.Models.TutorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.AdminProfile", b =>
                {
                    b.Navigation("ApprovedMemberships");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.Center", b =>
                {
                    b.Navigation("AdminProfiles");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.ClientProfile", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.TutorProfile", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TutoFlow.ApiService.Data.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("ClientProfile");

                    b.Navigation("TutorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
